
                    <a class="item" href="https://embedthis.com/">Embedthis</a>
                    <a class="item" href="https://embedthis.com/pak/">Pak Site</a>
                    <span class="desktop-only">
                        <a class="item" href="https://embedthis.com/blog/categories/Pak/">Pak News</a>
                        <a class="item" href="https://github.com/embedthis/pak">Repository</a>
                        <a class="item" href="https://embedthis.com/blog/">Blog</a>
                        <a class="item" href="https://twitter.com/embedthat">Twitter</a>
                    </span>
